### ISSUE TITLE
Newly created radio playlist is not shown properly/"Couldn't find that playlist" error

### ISSUE THREAD

**Issue by krzdabrowski** [BitesizedLion/AnonymizedRadios#3]
Hey, firstly I want to thank you for a great extension that brings back such a basic functionality back to Spotify 🙂

However, when generating newly created radio playlist, I'm getting two different types of bugs.

Steps to reproduce for first bug:
1. Navigate to playlist with "Stay Fly" by Three 6 Mafia song.
2. Click on "Create anonymized radio"
3. Wait few seconds with loading indicator.
4. It'll show an error, see screenshot provided:
<img width="360" alt="Screenshot 2023-11-09 at 22 01 52" src="https://github.com/BitesizedLion/AnonymizedRadios/assets/36383670/054d033b-0051-4613-b6e7-09880fea4f4d">

Steps to reproduce for second bug:
1. Navigate to any other songs.
2. Click on "Create anonymized radio"
3. It'll navigate to newly created playlist but it'll be always empty, see screenshot provided:
<img width="1304" alt="Screenshot 2023-11-09 at 22 09 54" src="https://github.com/BitesizedLion/AnonymizedRadios/assets/36383670/6b7249d9-45ef-4ac8-9cd6-6744a952474a">

Unfortunately I don't code in JavaScript so I'm not able to help with PR 😞

**Comment by BitesizedLion** [comment]
Hey there. Unsure if it's unrelated but Spotify seems to be having issues right now, could possibly be caused by that?

I'll take another look after the outage and see if I can reproduce it.

Thanks for the report.

**Comment by m3adow** [comment]
This is still happening. I assume Spoqify takes too long to generate the playlist.

**Comment by BitesizedLion** [comment]
Will look into it and see if I can do something about it.
